# Generated by Django 3.2.6 on 2021-08-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_plant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='plant',
        ),
    ]
